table d_order_payments
	lineageTag: 3ca353c1-12f1-45c9-83aa-59792bcb3db3

	column order_id
		dataType: string
		lineageTag: fbf02553-ae71-4aaa-956d-85d67e197f1a
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 83633661-876a-4212-b7c3-869b8326db9e
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 0a51f57d-78ba-4dfe-b87c-e1f7832dee46
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: 13f0e2e2-0b1b-4329-a316-35092563c5ce
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition d_order_payments = m
		mode: import
		queryGroup: Active
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\49151\OneDrive\Курс IT\Power BI\Project\Project-20241011T133917Z-001\Project\olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",".",",",Replacer.ReplaceText,{"payment_value"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"payment_value", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"payment_sequential"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

